name: 'Helm'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#   workflow_dispatch:
#     inputs:
#       job:
#         description: 'Job to run.'
#         required: true
#         default: 'Helm_Deploy'

permissions:
  contents: read

jobs:
  Helm_Template:
    runs-on: ubuntu-latest
    steps:
      #- name: Create k8s Kind Cluster
      - uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: kind 
        run: |
         kubectl get pods -n kube-system
  Helm_Lint:
    environment: 'dev'
    runs-on: ubuntu-latest
#     if: ${{ github.event.inputs.job == ' Helm_Lint'}}
    needs: Helm_Template
    steps:
      - uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: Helm Lint
        run: |
         helm install --dry-run --debug zelar zelar
  Helm_Deploy:
    needs: [Helm_Template, Helm_Lint]
    environment: 'prod'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: Helm Lint
        run: |
         helm install --dry-run --debug zelar zelar 

