name: 'Helm'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      #- name: Create k8s Kind Cluster
        #uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: kind 
        run: |
         kind create cluster --wait 300s
         kubectl wait --for=condition=Ready pods --all --namespace kube-system
         kubectl cluster-info
         kubectl get pods -n kube-system 
         ls 
         helm install zelar --generate-name
