name: 'Helm'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - name: Install helm
      run:  |
        curl -sSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm init --client-only
    
    - name: Add dependency chart repos
      run:  |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/


    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: 'zelar'
        token: '${{ github.token }}'
        values: |
          name: foobar
        value-files: >-
         [
          "values.yaml", 
          "values.production.yaml"
         ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
