name: 'Helm'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - name: 'Deploy'
      uses: 'deliverybot/helm@v2'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: 'zelar'
        token: '${{ github.token }}'
        values: |
          name: foobar
        value-files: >-
         [
          "values.yaml", 
          "values.production.yaml"
         ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
