name: 'Helm'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  Setting_up_kind_environment:
    runs-on: ubuntu-latest
    steps:
      #- name: Create k8s Kind Cluster
      - uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: kind 
        run: |
         kubectl get pods -n kube-system
  Helm_Lint:
    runs-on: ubuntu-latest
    #needs: Setting_up_kind_environment
    steps:
      - uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: Helm Lint
        run: |
         helm install --dry-run --debug zelar zelar
  Helm_Deploy:
    needs: [Setting_up_kind_environment, Helm_Lint]
    runs-on: ubuntu-latest
    steps:
      - uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: Helm Lint
        run: |
         helm install --dry-run --debug zelar zelar 
