name: 'Helm'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  Setting_up_kind_environment:
    runs-on: ubuntu-latest
    steps:
      #- name: Create k8s Kind Cluster
      #- uses: helm/kind-action@v1.3.0
      - uses: actions/checkout@master
      - name: kind 
        run: |
         kind create cluster --wait 300s
         export KUBECONFIG="$(kind get kubeconfig-path)"
         kind get kubeconfig-path
         kubectl wait --for=condition=Ready pods --all --namespace kube-system
         kubectl cluster-info
         kubectl get pods -n kube-system
#   Helm_Lint:
#     runs-on: ubuntu-latest
#     #needs: Setting_up_kind_environment
#     steps:
#       - uses: actions/checkout@master
#       - uses: helm/kind-action@v1.3.0
#       - name: Helm Lint
#         run: |
#          helm install --dry-run --debug zelar zelar 
#          helm install zelar --generate-name
#       - name: Helm Deploy 
#         run: |
#          helm install  --generate-name zelar 
#          kubectl get pods -A
          
