name: 'Helm'

on:
  push:
    branches:
    - "main"
  pull_request:

permissions:
  contents: read

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.3.0
